### PR TITLE
Non ia

### PR DESCRIPTION
**Pull request by AlexGKim**
Introduce a class that reads an sed file (SNANA format) and creates an sncosmo Source object.

### CODE REVIEW

**Comment by rbiswas4** [comment]
Also, is there an easy way to use this for cases where a built in exists, because SNCosmo stores them in partcular direcrtories?  This would be useful in applying this code across all cases.

**Comment by AlexGKim** [comment]
I understand your point, I think I know how to do this better that is consistent with how the built-ins are done.  Try to do this tomorrow.

Alex

**Comment by AlexGKim** [comment]
Rahul,

I think the solution for local supernova data files is run a local version
of builtins.py to add these objects to the registry.  So I don't think
there is anything new code that has to be written now.

Alex

**Comment by rbiswas4** [comment]
ok. I see ... I will merge and make a few cosmetic changes.

**Comment by AlexGKim** [comment]
Ah no, you didn't have to merge.  The code I sent is deprecated.

Alex

**Comment by rbiswas4** [comment]
OK ... I misunderstood and had merged and was making some changes (that I pushed). That is fine ... should not be an issue. One thing that I just thought of is that models may be a good name to change to sourcemodels, since sncosmo already has a models module. Sure, namespaces can be kept different, but it is nice to avoid collisions if we already know.

**Pull request merged**
